/**
 * Granular permissions. Every protected server action checks one of these
 * server-side (never rely on hiding UI buttons alone).
 */
export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  DC_CREATE: "DC_CREATE",
  DC_VIEW: "DC_VIEW",
  DC_EDIT: "DC_EDIT",
  DC_APPROVE: "DC_APPROVE",
  DC_CANCEL: "DC_CANCEL",
  DC_DISPATCH: "DC_DISPATCH",
  RECEIPT_CREATE: "RECEIPT_CREATE",
  RECEIPT_VIEW: "RECEIPT_VIEW",
  RECEIPT_EDIT: "RECEIPT_EDIT",
  RECEIPT_APPROVE: "RECEIPT_APPROVE",
  SCRAP_CREATE: "SCRAP_CREATE",
  SCRAP_VIEW: "SCRAP_VIEW",
  SCRAP_EDIT: "SCRAP_EDIT",
  SCRAP_APPROVE: "SCRAP_APPROVE",
  RECONCILIATION_VIEW: "RECONCILIATION_VIEW",
  RECONCILIATION_APPROVE: "RECONCILIATION_APPROVE",
  RECONCILIATION_CLOSE: "RECONCILIATION_CLOSE",
  RECONCILIATION_OVERRIDE: "RECONCILIATION_OVERRIDE",
  VENDOR_VIEW: "VENDOR_VIEW",
  VENDOR_CREATE: "VENDOR_CREATE",
  VENDOR_EDIT: "VENDOR_EDIT",
  ITEM_VIEW: "ITEM_VIEW",
  ITEM_CREATE: "ITEM_CREATE",
  ITEM_EDIT: "ITEM_EDIT",
  PROCESS_VIEW: "PROCESS_VIEW",
  PROCESS_CREATE: "PROCESS_CREATE",
  PROCESS_EDIT: "PROCESS_EDIT",
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_EXPORT: "REPORT_EXPORT",
  USER_MANAGE: "USER_MANAGE",
  ROLE_MANAGE: "ROLE_MANAGE",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
  AUDIT_VIEW: "AUDIT_VIEW",
  DOCUMENT_UPLOAD: "DOCUMENT_UPLOAD",
  DOCUMENT_DELETE: "DOCUMENT_DELETE",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const ROLES = {
  ADMIN: "ADMIN",
  STORES: "STORES",
  PURCHASE: "PURCHASE",
  PRODUCTION: "PRODUCTION",
  QUALITY: "QUALITY",
  ACCOUNTS: "ACCOUNTS",
  MANAGEMENT: "MANAGEMENT",
  VENDOR: "VENDOR",
} as const;

export type RoleKey = keyof typeof ROLES;

const P = PERMISSIONS;

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, string[]> = {
  ADMIN: Object.values(P),
  STORES: [
    P.DASHBOARD_VIEW,
    P.DC_CREATE, P.DC_VIEW, P.DC_EDIT, P.DC_DISPATCH,
    P.RECEIPT_CREATE, P.RECEIPT_VIEW,
    P.SCRAP_CREATE, P.SCRAP_VIEW,
    P.RECONCILIATION_VIEW,
    P.VENDOR_VIEW, P.ITEM_VIEW, P.PROCESS_VIEW,
  ],
  PURCHASE: [P.DASHBOARD_VIEW, P.VENDOR_VIEW, P.DC_VIEW, P.REPORT_VIEW, P.REPORT_EXPORT],
  PRODUCTION: [
    P.DASHBOARD_VIEW,
    P.DC_VIEW, P.PROCESS_VIEW, P.PROCESS_CREATE, P.PROCESS_EDIT,
    P.RECONCILIATION_VIEW, P.RECONCILIATION_APPROVE,
    P.ITEM_VIEW,
  ],
  QUALITY: [P.DASHBOARD_VIEW, P.RECEIPT_VIEW, P.RECEIPT_EDIT, P.RECONCILIATION_VIEW, P.DC_VIEW],
    ACCOUNTS: [P.DASHBOARD_VIEW, P.DC_VIEW, P.VENDOR_VIEW, P.REPORT_VIEW, P.REPORT_EXPORT],
  MANAGEMENT: [P.DASHBOARD_VIEW, P.DC_VIEW, P.VENDOR_VIEW, P.SCRAP_VIEW, P.REPORT_VIEW, P.REPORT_EXPORT, P.RECONCILIATION_VIEW],
  VENDOR: [P.DC_VIEW, P.RECEIPT_VIEW, P.SCRAP_VIEW],
};